[project]
name = "src"
version = "0.0.1"
description = "MLOps project for productionizing models"
authors = [{name = "Vikash Das", email = "swapnilforeverything@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}